### ISSUE TITLE
Dynamically get thumbnail for most recent comic

### ISSUE THREAD

**Issue by cvilbrandt** [ryanvilbrandt/comic_git#14]
I need a 200px x 150px thumbnail of the most recent comic to slot into the header.

I would like the algorithm to:
1. Resize the most recent comic to 600px wide (keep aspect ratio)
2. Locate a face
3. Crop centered around that face
4. Store it as a separate thumbnail

**Comment by ryanvilbrandt** [comment]
OpenCV would be required for this, and as far as I can tell it may not be possible to set up automatically for Github Pages. I would recommend this is something that the creator does manually, or with their own script.
