### ISSUE TITLE
Have a "No pages in this section" error text

### ISSUE THREAD

**Issue by cvilbrandt** [ryanvilbrandt/comic_git#19]
FTR, if you put in an archive section that has no pages yet, the build script breaks.

>   File "src/templates\infinite_scroll.tpl", line 5, in block "content"
>     {%- for section in archive_sections %}
>   File "C:\Users\artis\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 471, in getattr
>     return getattr(obj, attribute)
> jinja2.exceptions.UndefinedError: list object has no element 0

Especially for testing, it might be a good idea to have it print out a "No pages in this section" instead of breaking!

**Comment by ryanvilbrandt** [comment]
Obsolete now that storylines have been added
