### ISSUE TITLE
Center Infinite Scroll images

### ISSUE THREAD

**Issue by cvilbrandt** [ryanvilbrandt/comic_git#31]
Comic pages on the Infinite Scroll page don't automatically center. Because images display inline automatically, the usual margin: auto trick won't work unless you have them display as block. I propose the following fix:
```
#infinite-scroll a {
    max-width: 100%;
}
#infinite-scroll img {
    display: block;
    margin: auto;
}
```

**Comment by ryanvilbrandt** [comment]
Looks like it's centering on mine. Please put in an issue again if it happens again, and we can take a look on your computer.
