### ISSUE TITLE
REQUEST: Fanart Gallery Functionality

### ISSUE THREAD

**Issue by cvilbrandt** [ryanvilbrandt/comic_git#34]
### Problem
I often have weeks of guest comics or fanart that I want to, upon upload, intersperse with the main comic. It is important to me that guest comics/fanart (hereafter called 'fanart') gets front-and-center attention for at least a week when it's released.

However, once the main comic resumes, I don't want the flow of the story to be interrupted for  future readers. I want to remove the fanart from the main comic, but I don't want to delete the post/comments/etc, and I still want it to be accessible in another section of the website.

### Desired Workflow
I would like to be able to move the fanart post folders in the Your_Content/Comics folder to another folder (perhaps Your_Content/Fanart) and have it act as a secondary "comic" on the website, complete with an archive, and First/Previous/Next/Last navigation. I could then link the archive from the link bar, titled "Fanart" and people could peruse it and it could maintain front-and-center visibility without interrupting the comic.

I would not want it as a separate storyline, however, because I don't want it to be on its own section in the main comic archive. I want to keep that separate and streamlined.

### Most Important Functionality
More than anything, I just want to be able to move posts out of the main Comic folder and into what is, essentially, a gallery. Navigation is not a must-have. Just the ability to look at an archive and click to a post that is not a part of the main comic in any way.

If no navigation is available, a breadcrumb navigation should be included. e.g. at the top of the page, `Tamberlane > Fanart > MissJazdaFunk` so people can easily get back without using the back button. (Important UX/accessibility.)

### Nice-to-Haves
The comic-style navigation would be nice to have. 

### Suggestions + Expandability
If you're able to maintain a secondary "comic" like this, complete with separate navigation, it could allow folks to host multiple comics on one site/repo. That would be a high-demand feature, I expect.

**Comment by ryanvilbrandt** [comment]
Leaving this here for @cvilbrandt to verify that the Extra Comics functionality fulfills this request.

**Comment by ryanvilbrandt** [comment]
Confirmed with @cvilbrandt verbally that this is covered by the Extra Comic functionality.
